/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoprogra.igu;

/**
 *
 * @author totol
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clientesBTN = new javax.swing.JButton();
        ordenesBTN = new javax.swing.JButton();
        productosBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientesBTN.setBackground(new java.awt.Color(242, 242, 242));
        clientesBTN.setText("CLIENTES");
        clientesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesBTNActionPerformed(evt);
            }
        });
        jPanel1.add(clientesBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 256, 121));

        ordenesBTN.setBackground(new java.awt.Color(242, 242, 242));
        ordenesBTN.setText("ORDENES");
        ordenesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenesBTNActionPerformed(evt);
            }
        });
        jPanel1.add(ordenesBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 290, 245, 121));

        productosBTN.setBackground(new java.awt.Color(242, 242, 242));
        productosBTN.setText("PRODUCTOS");
        productosBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosBTNActionPerformed(evt);
            }
        });
        jPanel1.add(productosBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 288, 121));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatGPT Image 25 jun 2025, 03_13_09.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1310, 890));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesBTNActionPerformed
        ventanaCliente ventanaClientes = new ventanaCliente(this);
        ventanaClientes.setLocationRelativeTo(null);
        ventanaClientes.setVisible(true);
    }//GEN-LAST:event_clientesBTNActionPerformed

    private void ordenesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenesBTNActionPerformed
        
        ventanaOrdenes ventanaOrdenes = new ventanaOrdenes(this);
        ventanaOrdenes.setVisible(true);
        ventanaOrdenes.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_ordenesBTNActionPerformed

    private void productosBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosBTNActionPerformed
        ventanaProductos ventanaProductos = new ventanaProductos(this);
        ventanaProductos.setVisible(true);
        ventanaProductos.setLocationRelativeTo(null);
    }//GEN-LAST:event_productosBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientesBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ordenesBTN;
    private javax.swing.JButton productosBTN;
    // End of variables declaration//GEN-END:variables
}
